# Generated by Django 6.1.1 on 2026-09-24 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('isbn', models.CharField(help_text='Código ISBN.', max_length=17, unique=True, verbose_name='ISBN')),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Costo (USD)')),
                ('selling_price_local', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Precio (Local)')),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoría')),
                ('supplier_country', models.CharField(blank=True, help_text='Código ISO de 2 letras, ej: ES, US', max_length=2, verbose_name='País Proveedor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['-created_at'],
            },
        ),
    ]
